spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/groupbuy?serverTimezone=UTC
    username: root
    password: 12345678

server:
  port: 12345

mybatis:
  configuration:
    map-underscore-to-camel-case: true